# Generated by Django 5.0.6 on 2024-05-28 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_uuid_head',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_uuid_tribe',
            field=models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
