# Generated by Django 5.0.6 on 2024-05-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ref_account_id_head',
        ),
    ]
