# Generated by Django 5.0.6 on 2024-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legal_agree',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
