# Generated by Django 5.0.6 on 2024-05-28 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_ref_account_id_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_account_id_head',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
