# Generated by Django 5.0.6 on 2024-05-29 13:47

import django.db.models.deletion
import lib.fallbacks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_ref_uuid_head_alter_user_ref_uuid_tribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ref_uuid_tribe',
        ),
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.URLField(default=lib.fallbacks.default_profile_image),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_uuid_head',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
