# Generated by Django 5.0.6 on 2024-05-29 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_ref_uuid_tribe_alter_user_image_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_uuid_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
