# Generated by Django 5.0.6 on 2024-05-28 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_access_level_alter_user_image_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_account_id_head',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
