# Generated by Django 5.0.6 on 2024-06-12 16:35

import lib.fallbacks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_access_level_alter_user_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.URLField(blank=True, default=lib.fallbacks.default_profile_image, null=True),
        ),
    ]
