# Generated by Django 5.0.6 on 2024-06-12 16:37

import lib.fallbacks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.URLField(default=lib.fallbacks.default_profile_image),
        ),
    ]
