# Generated by Django 5.0.6 on 2024-05-28 23:25

import comments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField()),
                ('audio_url', models.CharField(blank=True, null=True)),
                ('ref_uuid_owner', models.ForeignKey(on_delete=models.SET_NULL, related_name='comments_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
