# Generated by Django 5.0.6 on 2024-05-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('goals_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ref_goal_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='goals_log.goallog'),
        ),
    ]
