# Generated by Django 5.0.6 on 2024-05-29 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_audio_url_alter_comment_text'),
        ('goals_log', '0001_initial'),
        ('tasks_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ref_goal_log_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='goals_log.goallog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ref_task_log_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='tasks_log.tasklog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ref_uuid_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
