# Generated by Django 5.0.6 on 2024-05-31 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
        ('goals_log', '0002_initial'),
        ('tasks_log', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ref_goal_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goals_log.goallog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ref_task_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks_log.tasklog'),
        ),
    ]
