# Generated by Django 5.0.6 on 2024-05-29 15:03

import datetime
import django.db.models.deletion
import lib.fallbacks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards_define', '0002_alter_rewarddefine_image1_and_more'),
        ('stories', '0002_alter_story_items_artwork_alter_story_scenes_artwork_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('image1', models.URLField(default=models.SET(lib.fallbacks.default_goal_log_image))),
                ('notes', models.TextField(blank=True, null=True)),
                ('reward_is_claimed', models.BooleanField(default=False)),
                ('timestamp_reward_claimed', models.DateTimeField(blank=True, null=True)),
                ('ref_reward_define_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_goals', to='rewards_define.rewarddefine')),
                ('ref_story_id', models.ForeignKey(on_delete=models.SET(lib.fallbacks.default_story_id), related_name='related_goals', to='stories.story')),
                ('ref_uuid_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_created', to=settings.AUTH_USER_MODEL)),
                ('refs_uuid_assignees', models.ManyToManyField(related_name='goals_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
