# Generated by Django 5.0.6 on 2024-05-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_log', '0001_initial'),
        ('rewards_define', '0003_rewarddefine_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goallog',
            name='ref_reward_define_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_goals', to='rewards_define.rewarddefine'),
        ),
    ]
