# Generated by Django 5.0.6 on 2024-05-30 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals_log', '0001_initial'),
        ('rewards_define', '0001_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goallog',
            name='ref_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goallog',
            name='ref_rewards_define',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_goals', to='rewards_define.rewarddefine'),
        ),
        migrations.AddField(
            model_name='goallog',
            name='ref_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_goals', to='stories.story'),
        ),
        migrations.AddField(
            model_name='goallog',
            name='refs_assignees',
            field=models.ManyToManyField(related_name='goals_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
