# Generated by Django 5.0.6 on 2024-06-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals_log', '0004_alter_goallog_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goallog',
            old_name='ref_rewards_define',
            new_name='ref_reward_define',
        ),
    ]
