# Generated by Django 5.0.6 on 2024-06-11 20:35

import lib.fallbacks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_log', '0005_rename_ref_rewards_define_goallog_ref_reward_define'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goallog',
            name='image1',
            field=models.URLField(default=lib.fallbacks.default_goal_log_image),
        ),
    ]
