# Generated by Django 5.0.6 on 2024-05-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.PositiveIntegerField()),
                ('about', models.TextField()),
                ('scenes_narrative', models.TextField()),
                ('scenes_artwork', models.TextField()),
                ('items_artwork', models.TextField()),
            ],
        ),
    ]
