# Generated by Django 5.0.6 on 2024-05-30 11:50

import lib.fallbacks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardDefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField()),
                ('title_audio_url', models.URLField(blank=True, null=True)),
                ('image1', models.URLField(default=models.SET(lib.fallbacks.default_reward_def_image))),
                ('value', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('description_audio_url', models.URLField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('timestamp_archived', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
