# Generated by Django 5.0.6 on 2024-05-29 11:00

import rewards_define.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardDefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField()),
                ('image1', models.ImageField(default=models.SET(rewards_define.models.default_reward_def_image), upload_to='')),
                ('value', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('timestamp_archived', models.DateTimeField(blank=True, null=True)),
                ('ref_uuid_owner', models.ForeignKey(on_delete=models.SET_NULL, related_name='rewards_defined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
