# Generated by Django 5.0.6 on 2024-05-29 15:03

import django.db.models.deletion
import lib.fallbacks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_define', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarddefine',
            name='image1',
            field=models.URLField(default=models.SET(lib.fallbacks.default_reward_def_image)),
        ),
        migrations.AlterField(
            model_name='rewarddefine',
            name='ref_uuid_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_defined', to=settings.AUTH_USER_MODEL),
        ),
    ]
