# Generated by Django 5.0.6 on 2024-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_define', '0002_alter_rewarddefine_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarddefine',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
