# Generated by Django 5.0.6 on 2024-06-05 17:29

import lib.fallbacks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_define', '0003_alter_rewarddefine_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarddefine',
            name='image1',
            field=models.URLField(blank=True, default=lib.fallbacks.default_reward_def_image),
        ),
    ]
