# Generated by Django 5.0.6 on 2024-05-29 15:03

import django.db.models.deletion
import lib.fallbacks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField()),
                ('image1', models.URLField(default=models.SET(lib.fallbacks.default_task_def_image))),
                ('value', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('timestamp_archived', models.DateTimeField(blank=True, null=True)),
                ('ref_uuid_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_defined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
