# Generated by Django 5.0.6 on 2024-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_define', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdefine',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
