# Generated by Django 5.0.6 on 2024-06-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_define', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdefine',
            name='image1',
            field=models.URLField(),
        ),
    ]
