# Generated by Django 5.0.6 on 2024-06-03 10:23

import lib.fallbacks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_define', '0003_alter_taskdefine_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdefine',
            name='image1',
            field=models.URLField(default=lib.fallbacks.default_task_def_image),
        ),
    ]
