# Generated by Django 5.0.6 on 2024-05-30 11:50

import django.db.models.deletion
import lib.fallbacks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image1', models.URLField(default=models.SET(lib.fallbacks.default_task_log_image))),
                ('image2', models.URLField(blank=True, null=True)),
                ('ref_goal_log', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_goal', to='goals_log.goallog')),
            ],
        ),
    ]
