# Generated by Django 5.0.6 on 2024-05-29 15:03

import django.db.models.deletion
import lib.fallbacks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals_log', '0001_initial'),
        ('tasks_define', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image1', models.URLField(default=models.SET(lib.fallbacks.default_task_log_image))),
                ('image2', models.URLField(blank=True, null=True)),
                ('ref_goal_log_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_goal', to='goals_log.goallog')),
                ('ref_task_define_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tasks_created', to='tasks_define.taskdefine')),
                ('ref_uuid_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_logged', to=settings.AUTH_USER_MODEL)),
                ('refs_uuid_assignees', models.ManyToManyField(related_name='tasks_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
