# Generated by Django 5.0.6 on 2024-05-30 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks_define', '0002_initial'),
        ('tasks_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='ref_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_logged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='ref_task_define',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to='tasks_define.taskdefine'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='refs_assignees',
            field=models.ManyToManyField(related_name='tasks_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
