# Generated by Django 5.0.6 on 2024-05-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_define', '0002_taskdefine_is_hidden'),
        ('tasks_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='ref_task_define_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to='tasks_define.taskdefine'),
        ),
    ]
