# Generated by Django 5.0.6 on 2024-06-04 08:49

import lib.fallbacks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_log', '0003_alter_tasklog_ref_goal_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='image1',
            field=models.URLField(default=lib.fallbacks.default_task_log_image),
        ),
    ]
